# Generated by Django 3.2.12 on 2023-12-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=80)),
                ('number', models.IntegerField()),
                ('current_date', models.DateField()),
            ],
        ),
    ]
