# Generated by Django 4.2.8 on 2024-02-06 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerLeftScore', models.IntegerField(default=0)),
                ('playerRightScore', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('FINISHED', 'Finished')], default='WAITING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('playerLeft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerLeft', to=settings.AUTH_USER_MODEL)),
                ('playerRight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerRight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
