# Generated by Django 4.2.8 on 2024-02-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In Progress'), ('PAUSED', 'Paused'), ('FINISHED', 'Finished')], default='WAITING', max_length=20),
        ),
    ]
