# Generated by Django 4.2.7 on 2023-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_42_user',
            field=models.BooleanField(default=False),
        ),
    ]
