# Generated by Django 4.2.7 on 2023-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='test',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
