# Generated by Django 4.2.7 on 2023-12-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_is_42_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
